version: '2.3'
services:
  wso2ei-mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    hostname: wso2ei-mysql
    ports:
      - 3306
    networks:
      - backend
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      # mounting MySQL init scripts
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      # mounting MySQL DB data
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  wso2ei-integrator:
    image: wso2ei-integrator:6.1.1
    container_name: wso2ei-integrator
    hostname: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    volumes:
      # mounting third-party libraries
      - ./integrator/lib/mysql-connector-java-5.1.45-bin.jar:/opt/wso2ei-6.1.1/lib/mysql-connector-java-5.1.45-bin.jar
      # mounting configurations
      - ./integrator/conf/datasources/master-datasources.xml:/opt/wso2ei-6.1.1/conf/datasources/master-datasources.xml
      - ./integrator/conf/user-mgt.xml:/opt/wso2ei-6.1.1/conf/user-mgt.xml
      - ./integrator/conf/registry.xml:/opt/wso2ei-6.1.1/conf/registry.xml
      - ./integrator/conf/synapse.properties:/opt/wso2ei-6.1.1/conf/synapse.properties
      - ./integrator/conf/carbon.xml:/opt/wso2ei-6.1.1/conf/carbon.xml
      - ./integrator/conf/axis2/axis2.xml:/opt/wso2ei-6.1.1/conf/axis2/axis2.xml
      # mounting carbon apps
      - ./integrator/repository/deployment/server/carbonapps:/opt/wso2ei-6.1.1/repository/deployment/server/carbonapps
      # mounting analytics event publishers
      - ./integrator/repository/deployment/server/eventpublishers:/opt/wso2ei-6.1.1/repository/deployment/server/eventpublishers
      # mounting synapse artifacts
      - ./integrator/repository/deployment/server/synapse-configs:/opt/wso2ei-6.1.1/repository/deployment/server/synapse-configs
      # mounting keystores
      - ./integrator/repository/resources/security/wso2carbon.jks:/opt/wso2ei-6.1.1/epository/resources/security/wso2carbon.jks
      - ./integrator/repository/resources/security/client-truststore.jks:/opt/wso2ei-6.1.1/repository/resources/security/client-truststore.jks
    depends_on:
      wso2ei-mysql:
        condition: service_healthy

networks:
  frontend:
  backend:
